export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PAGINATE_DATA = 'SET_PAGINATE_DATA';

export const ADD_FILTER = 'ADD_FILTER';
export const ADD_ADVANCED_SEARCH = 'ADD_ADVANCED_SEARCH';
export const ADD_SORT = 'ADD_SORT';
export const SET_FILTERS = 'SET_FILTERS';
export const SET_MENU = 'SET_MENU';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const UPDATE_FILTERCOLUMN = 'UPDATE_FILTERCOLUMN';
export const UPDATE_FILTERTYPE = 'UPDATE_FILTERTYPE';
export const UPDATE_FILTERVALUE = 'UPDATE_FILTERVALUE';
export const UPDATE_LOGICAL_OPERATOR = 'UPDATE_LOGICAL_OPERATOR';
export const UPDATE_NOTOPERATOR = 'UPDATE_NOTOPERATOR';

export const ADD_DRAG_RESIZE = 'ADD_DRAG_RESIZE';
export const REMOVE_DRAG_RESIZE = 'REMOVE_DRAG_RESIZE';
export const UPDATE_DRAG_RESIZE = 'UPDATE_DRAG_RESIZE';   

export const SET_MENUBAR = 'SET_MENUBAR';